### ISSUE TITLE
Participation rewards panic on nil allocation

### ISSUE THREAD

**Issue by joe-bowman** [ingenuity-build/quicksilver#104]
```
5:21PM INF getZoneAllocations allocation=[] module=x/participationrewards proportions={"qscosmos-2":"1.000000000000000000"}
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types.Coins.GetDenomByIndex(...)
        github.com/cosmos/cosmos-sdk@v0.45.4/types/coin.go:649
github.com/ingenuity-build/quicksilver/x/participationrewards/keeper.Keeper.getZoneAllocations({{0x258a3c8, 0xc0010e99a0}, {0x256b7f0, 0xc000e745e0}, {{0x258a3c8, 0xc0010e99a0}, 0xc000011b38, {0x256b7f0, 0xc000e74510}, {0x256b840, ...}, ...}, ...}, ...)
        github.com/ingenuity-build/quicksilver/x/participationrewards/keeper/distribution.go:212 +0x40d
github.com/ingenuity-build/quicksilver/x/participationrewards/keeper.Keeper.allocateValidatorSelectionRewards({{0x258a3c8, 0xc0010e99a0}, {0x256b7f0, 0xc000e745e0}, {{0x258a3c8, 0xc0010e99a0}, 0xc000011b38, {0x256b7f0, 0xc000e74510}, {0x256b840, ...}, ...}, ...}, ...)
        github.com/ingenuity-build/quicksilver/x/participationrewards/keeper/rewards_validatorSelection.go:53 +0x238
github.com/ingenuity-build/quicksilver/x/participationrewards/keeper.Keeper.allocateZoneRewards({{0x258a3c8, 0xc0010e99a0}, {0x256b7f0, 0xc000e745e0}, {{0x258a3c8, 0xc0010e99a0}, 0xc000011b38, {0x256b7f0, 0xc000e74510}, {0x256b840, ...}, ...}, ...}, ...)
        github.com/ingenuity-build/quicksilver/x/participationrewards/keeper/distribution.go:157 +0x289
github.com/ingenuity-build/quicksilver/x/participationrewards/keeper.Keeper.AfterEpochEnd({{0x258a3c8, 0xc0010e99a0}, {0x256b7f0, 0xc000e745e0}, {{0x258a3c8, 0xc0010e99a0}, 0xc000011b38, {0x256b7f0, 0xc000e74510}, {0x256b840, ...}, ...}, ...}, ...)
        github.com/ingenuity-build/quicksilver/x/participationrewards/keeper/hooks.go:39 +0x350
github.com/ingenuity-build/quicksilver/x/participationrewards/keeper.Hooks.AfterEpochEnd(...)
        github.com/ingenuity-build/quicksilver/x/participationrewards/keeper/hooks.go:68
github.com/ingenuity-build/quicksilver/x/epochs/types.MultiEpochHooks.AfterEpochEnd(...)
        github.com/ingenuity-build/quicksilver/x/epochs/types/hooks.go:26
github.com/ingenuity-build/quicksilver/x/epochs/keeper.Keeper.AfterEpochEnd(...)
        github.com/ingenuity-build/quicksilver/x/epochs/keeper/hooks.go:9
github.com/ingenuity-build/quicksilver/x/epochs/keeper.Keeper.BeginBlocker.func1(0xc003931ba0?, {{0xc000114c0a, 0x5}, {0x0, 0xeda3a6f40, 0x0}, 0x4e94914f0000, 0x1, {0x0, 0xeda3a6f40, ...}, ...})
        github.com/ingenuity-build/quicksilver/x/epochs/keeper/abci.go:39 +0xf99
github.com/ingenuity-build/quicksilver/x/epochs/keeper.Keeper.IterateEpochInfo({{_, _}, {_, _}, {_, _}}, {{0x257f190, 0xc000052060}, {0x258bc20, 0xc0033b5040}, ...}, ...)
        github.com/ingenuity-build/quicksilver/x/epochs/keeper/epoch.go:49 +0x2a7
github.com/ingenuity-build/quicksilver/x/epochs/keeper.Keeper.BeginBlocker({{_, _}, {_, _}, {_, _}}, {{0x257f190, 0xc000052060}, {0x258bc20, 0xc0033b5040}, ...})
        github.com/ingenuity-build/quicksilver/x/epochs/keeper/abci.go:17 +0x24d
github.com/ingenuity-build/quicksilver/x/epochs.AppModule.BeginBlock(...)
        github.com/ingenuity-build/quicksilver/x/epochs/module.go:159
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x257f190, 0xc000052060}, {0x258bc20, 0xc0033b5040}, {{0xb, 0x0}, {0xc000e9c4c0, 0xa}, 0x3e2a, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:479 +0x3a2
github.com/ingenuity-build/quicksilver/app.(*Quicksilver).BeginBlocker(_, {{0x257f190, 0xc000052060}, {0x258bc20, 0xc0033b5040}, {{0xb, 0x0}, {0xc000e9c4c0, 0xa}, 0x3e2a, ...}, ...}, ...)
        github.com/ingenuity-build/quicksilver/app/app.go:717 +0x98
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc004520ba0, 0x20, 0x20}, {{0xb, 0x0}, {0xc000e9c4c0, 0xa}, 0x3e2a, {0xa22c9ae, ...}, ...}, ...})
        github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:194 +0x97c
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc004520ba0, 0x20, 0x20}, {{0xb, 0x0}, {0xc000e9c4c0, 0xa}, 0x3e2a, {0xa22c9ae, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc004520ba0, 0x20, 0x20}, {{0xb, 0x0}, {0xc000e9c4c0, 0xa}, 0x3e2a, {0xa22c9ae, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x257ff20?, 0xc000e311a0}, {0x2585050, 0xc000dceec0}, 0xc000000d20, {0x258af28, 0xc001019400}, 0x3e29?)
        github.com/tendermint/tendermint@v0.34.19/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc003912c90, 0x8}}, {0xc003912ca0, 0xa}, 0x1, 0x3e29, {{0xc003930400, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.19/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc003912c90, 0x8}}, {0xc003912ca0, 0xa}, 0x1, 0x3e29, {{0xc003930400, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc003912c90, 0x8}}, {0xc003912ca0, 0xa}, 0x1, 0x3e29, {{0xc003930400, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0033cdfd0, {0x258c3f8, 0xc000cfcc30})
        github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc003912c90, 0x8}}, {0xc003912ca0, 0xa}, 0x1, 0x3e29, ...}, ...)
        github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000cc3400, {0x257c050, 0xc000549180}, 0xc000ec8640, {0x2566ae0, 0xc00391be00}, 0x0?, 0x0?, 0xc000ec88e0, {0x257ff20, ...}, ...)
        github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2592c88, 0xc000539bf0}, {0xc00050f2e0, 0xa}, {0x2582e48, 0xc001091b60}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000cdc000?, {0x33af4f8?, 0x0?, 0x0?})
        github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc000cdc000, {0x33af4f8, 0x0, 0x0})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc001022c80)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc00104b5a0, 0x1d})
        github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
        github.com/ingenuity-build/quicksilver/cmd/quicksilverd/main.go:20 +0x38
```

**Comment by joe-bowman** [comment]
This issue was triggered as a result of: https://github.com/ingenuity-build/testnets/blob/93d2082ede223267ce1a9c8715381d5e7aa780a1/rhapsody/genesis.json#L555

The `mint` epoch name was `day`, whereas the epoch used was called `epoch`. As a result, no allocation was minted - which meant that the above logic failed when it otherwise would not have. 

That said; we should guard against unexpected values.
