### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bowman761** [ingenuity-build/quicksilver#116]
quicksilverd has crashed five times today with a panic;

```
Jun 24 15:01:18 quicksilver quicksilverd[201385]: 3:01PM ERR CONSENSUS FAILURE!!! err="unable to delete version 16500 with 1 active readers" module=consensus stack="goroutine 227 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermi>
Jun 24 15:01:18 quicksilver quicksilverd[201385]: 3:01PM INF Stopping baseWAL service impl={"Logger":{}} module=consensus wal=/home/george/.quicksilverd/data/cs.wal/wal
Jun 24 15:01:18 quicksilver quicksilverd[201385]: 3:01PM INF Stopping Group service impl={"Dir":"/home/george/.quicksilverd/data/cs.wal","Head":{"ID":"UxkUeEvTQebj:/home/george/.quicksilverd/data/cs.wal/wal","Path":"/home/george/.quicksilverd/data/cs.wal/wal"},"ID":"group:UxkUeE>
Jun 24 15:01:19 quicksilver quicksilverd[201385]: 3:01PM INF Timed out dur=3000 height=16510 module=consensus round=0 step=3
Jun 24 15:01:28 quicksilver quicksilverd[201385]: 3:01PM INF Transactions per second tps=0.2
Jun 24 15:01:29 quicksilver quicksilverd[201385]: 3:01PM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"d19c75f8badc81d33e6d690d45106ee3521e555d","ip":"65.108.52.145","port":26656}
Jun 24 15:01:29 quicksilver quicksilverd[201385]: 3:01PM ERR Stopping peer for error err="read tcp 10.10.1.67:42098->65.108.52.145:26656: read: connection reset by peer" module=p2p peer={"Data":{},"Logger":{}}
Jun 24 15:01:29 quicksilver quicksilverd[201385]: 3:01PM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"d19c75f8badc81d33e6d690d45106ee3521e555d","ip":"65.108.52.145","port":26656}
Jun 24 15:01:41 quicksilver quicksilverd[201385]: 3:01PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=9 numToDial=1
Jun 24 15:01:41 quicksilver quicksilverd[201385]: 3:01PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
Jun 24 15:01:41 quicksilver quicksilverd[201385]: 3:01PM INF Dialing peer address={"id":"27daf4b8e45fe63dc94ffa4723ca901ca90946c4","ip":"168.119.248.8","port":26656} module=p2p
Jun 24 15:01:42 quicksilver quicksilverd[201385]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 24 15:01:42 quicksilver quicksilverd[201385]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdd6ab3]
Jun 24 15:01:42 quicksilver quicksilverd[201385]: goroutine 20058752 [running]:
Jun 24 15:01:42 quicksilver quicksilverd[201385]: github.com/cosmos/iavl.(*nodeDB).incrVersionReaders(0x2592ab0?, 0x20?)
Jun 24 15:01:42 quicksilver quicksilverd[201385]:         github.com/cosmos/iavl@v0.17.3/nodedb.go:619 +0x33
Jun 24 15:01:42 quicksilver quicksilverd[201385]: github.com/cosmos/iavl.newExporter(0xc01bb92168)
Jun 24 15:01:42 quicksilver quicksilverd[201385]:         github.com/cosmos/iavl@v0.17.3/export.go:45 +0xc8
Jun 24 15:01:42 quicksilver quicksilverd[201385]: github.com/cosmos/iavl.(*ImmutableTree).Export(...)
Jun 24 15:01:42 quicksilver quicksilverd[201385]:         github.com/cosmos/iavl@v0.17.3/immutable_tree.go:142
Jun 24 15:01:42 quicksilver quicksilverd[201385]: github.com/cosmos/cosmos-sdk/store/iavl.(*Store).Export(0xc00a35f080?, 0x2582980?)
Jun 24 15:01:42 quicksilver quicksilverd[201385]:         github.com/cosmos/cosmos-sdk@v0.45.4/store/iavl/store.go:248 +0x52
Jun 24 15:01:42 quicksilver quicksilverd[201385]: github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Snapshot(0xc000538dc0, 0x4074, {0x2579440, 0xc0069f8570})
Jun 24 15:01:42 quicksilver quicksilverd[201385]:         github.com/cosmos/cosmos-sdk@v0.45.4/store/rootmulti/store.go:693 +0x551
Jun 24 15:01:42 quicksilver quicksilverd[201385]: github.com/cosmos/cosmos-sdk/snapshots.(*Manager).createSnapshot(0xc0005222a0, 0xc027a5da40?, 0xc004ce9758?)
Jun 24 15:01:42 quicksilver quicksilverd[201385]:         github.com/cosmos/cosmos-sdk@v0.45.4/snapshots/manager.go:180 +0xb1
Jun 24 15:01:42 quicksilver quicksilverd[201385]: created by github.com/cosmos/cosmos-sdk/snapshots.(*Manager).Create
Jun 24 15:01:42 quicksilver quicksilverd[201385]:         github.com/cosmos/cosmos-sdk@v0.45.4/snapshots/manager.go:167 +0x1ee
Jun 24 15:01:42 quicksilver systemd[1]: quicksilver.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 24 15:01:42 quicksilver systemd[1]: quicksilver.service: Failed with result 'exit-code'.
Jun 24 15:01:43 quicksilver systemd[1]: quicksilver.service: Scheduled restart job, restart counter is at 5.
Jun 24 15:01:43 quicksilver systemd[1]: Stopped Quicksilver Validator.
```

**Comment by faddat** [comment]
I bet that you can close this now, I haven't seen this happen in the test net.

**Comment by bowman761** [comment]
Setting snapshot-interval = 0 resolved issue.
