### ISSUE TITLE
Bug: Div by zero fix doesn't cater for zero-length slice

### ISSUE THREAD

**Issue by joe-bowman** [ingenuity-build/quicksilver#224]
Panic thrown in attempt to avoid div-by-zero:
```
Aug 30 22:29:23 val01-qck-t quicksilverd[442584]: 10:29PM INF handling epoch end module=x/interchainstaking
Aug 30 22:29:23 val01-qck-t quicksilverd[442584]: 10:29PM INF MakeRequest callback=epochblock chain_id=fauxgaia-1 connection_id=connection-0 module=interchainstaking period=-1 query_type=cosmos.base.tendermint.v1beta1.Service/GetLatestBlock request= ttl=0
Aug 30 22:29:23 val01-qck-t quicksilverd[442584]: 10:29PM INF taking a snapshot of intents module=x/interchainstaking
Aug 30 22:29:23 val01-qck-t quicksilverd[442584]: panic: ordinalized intent sum is zero, this should never happen
Aug 30 22:29:23 val01-qck-t quicksilverd[442584]: goroutine 1 [running]:
Aug 30 22:29:23 val01-qck-t quicksilverd[442584]: github.com/ingenuity-build/quicksilver/x/interchainstaking/keeper.(*Keeper).AggregateIntents(_, {{0x26d8770, 0xc000052090}, {0x26e5980, 0xc0066b2700}, {{0xb, 0x0}, {0xc0010c9ca0, 0xa}, 0x217f0, ...}, ...}, ...)
Aug 30 22:29:23 val01-qck-t quicksilverd[442584]:         github.com/ingenuity-build/quicksilver/x/interchainstaking/keeper/intent.go:130 +0x57b
Aug 30 22:29:23 val01-qck-t quicksilverd[442584]: github.com/ingenuity-build/quicksilver/x/interchainstaking/keeper.Keeper.AfterEpochEnd.func1(_, {{0xc001b065d0, 0xc}, {0xc001b065e0, 0xa}, 0xc001a49180, 0xc001a491d0, 0xc001a49220, {0xc0018a3000, 0x64, ...}, ...})
Aug 30 22:29:23 val01-qck-t quicksilverd[442584]:         github.com/ingenuity-build/quicksilver/x/interchainstaking/keeper/hooks.go:37 +0x2e5
Aug 30 22:29:23 val01-qck-t quicksilverd[442584]: github.com/ingenuity-build/quicksilver/x/interchainstaking/keeper.Keeper.IterateZones({{0x26e72f8, 0xc0001513c0}, {0x26c31f0, 0xc00127e750}, {{0x26e4128, 0xc0001513c0}, {0x26c31f0, 0xc00127e6d0}, {0x26c3218, 0xc00127e7c0}, ...}, ...}, ...)
```

In #192 we add a panic to `x/interchainstaking/keeper/intents.go:aggregateIntents()` to avoid the potential div by zero; however, we did not cater for the case where by `intents` in a zero-length slice (no intents have ever been set) and thus the sum can legitimately be zero without triggering the div-by-zero error.

**Comment by joe-bowman** [comment]
This bug triggered a consensus failure in the Innuendo-1 testnet on 2022-08-30 at 20:00 UTC (epoch boundary)
