### ISSUE TITLE
x/airdrop: panic for staking claim

### ISSUE THREAD

**Issue by joe-bowman** [ingenuity-build/quicksilver#231]
Claiming type 6 (under successful conditions) fails with the following panic:

```
raw_log: "recovered: assignment to entry in nil map\nstack:\ngoroutine 32396 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24
  +0x65\ngithub.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x1ae7500,
  0x26bbba0})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.6/baseapp/recovery.go:71 +0x27\ngithub.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x1ae7500?,
  0x26bbba0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.6/baseapp/recovery.go:39 +0x30\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1ae7500,
  0x26bbba0}, 0xc04bb3a240?)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.6/baseapp/recovery.go:28
  +0x37\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1ae7500, 0x26bbba0},
  0x26e4c80?)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.6/baseapp/recovery.go:33 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.45.6/baseapp/baseapp.go:608
  +0xfd\npanic({0x1ae7500, 0x26bbba0})\n\truntime/panic.go:838 +0x207\ngithub.com/ingenuity-build/quicksilver/x/airdrop/keeper.Keeper.getClaimAmountAndUpdateRecord({{0x26e3428,
  0xc000c0c000}, {0x26c24f0, 0xc000c0d180}, {{0x26e3428, 0xc000c0c000}, 0xc000010010,
  {0x26c24f0, 0xc000c0d040}, {0x26c2540, ...}, ...}, ...}, ...)\n\tgithub.com/ingenuity-build/quicksilver/x/airdrop/keeper/claim_handler.go:401
  +0x1c5\ngithub.com/ingenuity-build/quicksilver/x/airdrop/keeper.Keeper.completeClaim({{0x26e3428,
  0xc000c0c000}, {0x26c24f0, 0xc000c0d180}, {{0x26e3428, 0xc000c0c000}, 0xc000010010,
  {0x26c24f0, 0xc000c0d040}, {0x26c2540, ...}, ...}, ...}, ...)\n\tgithub.com/ingenuity-build/quicksilver/x/airdrop/keeper/claim_handler.go:339
  +0x99\ngithub.com/ingenuity-build/quicksilver/x/airdrop/keeper.Keeper.handleBondedDelegation({{0x26e3428,
  0xc000c0c000}, {0x26c24f0, 0xc000c0d180}, {{0x26e3428, 0xc000c0c000}, 0xc000010010,
  {0x26c24f0, 0xc000c0d040}, {0x26c2540, ...}, ...}, ...}, ...)\n\tgithub.com/ingenuity-build/quicksilver/x/airdrop/keeper/claim_handler.go:82
  +0x12c\ngithub.com/ingenuity-build/quicksilver/x/airdrop/keeper.Keeper.HandleClaim({{0x26e3428,
  0xc000c0c000}, {0x26c24f0, 0xc000c0d180}, {{0x26e3428, 0xc000c0c000}, 0xc000010010,
  {0x26c24f0, 0xc000c0d040}, {0x26c2540, ...}, ...}, ...}, ...)\n\tgithub.com/ingenuity-build/quicksilver/x/airdrop/keeper/claim_handler.go:47
  +0x3e5\ngithub.com/ingenuity-build/quicksilver/x/airdrop/keeper.Keeper.Claim({{0x26e3428,
  0xc000c0c000}, {0x26c24f0, 0xc000c0d180}, {{0x26e3428, 0xc000c0c000}, 0xc000010010,
  {0x26c24f0, 0xc000c0d040}, {0x26c2540, ...}, ...}, ...}, ...)\n\tgithub.com/ingenuity-build/quicksilver/x/airdrop/keeper/claim_record.go:225
  +0x474\ngithub.com/ingenuity-build/quicksilver/x/airdrop/keeper.msgServer.Claim({0x410f25?},
  {0x26d7ae0?, 0xc044db2090?}, 0xc012991d40)\n\tgithub.com/ingenuity-build/quicksilver/x/airdrop/keeper/msg_server.go:28
  +0x205\ngithub.com/ingenuity-build/quicksilver/x/airdrop/types._Msg_Claim_Handler.func1({0x26d7ae0,
  0xc044db2090}, {0x1cbfe40?, 0xc012991d40})\n\tgithub.com/ingenuity-build/quicksilver/x/airdrop/types/messages.pb.go:262
  +0x78\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x26d7ae0,
  0xc044db2030}, {0x530c06?, 0x41096b?}, 0x1d1fd80?, 0xc0132ae768)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.6/baseapp/msg_service_router.go:113
  +0xdb\ngithub.com/ingenuity-build/quicksilver/x/airdrop/types._Msg_Claim_Handler({0x1d1e380?,
  0xc00012a3c0}, {0x26d7ae0, 0xc044db2030}, 0x241fbc8, 0xc0154244a0)\n\tgithub.com/ingenuity-build/quicksilver/x/airdrop/types/messages.pb.go:264
  +0x138\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x26d7a70,
  0xc000130020}, {0x26e4c80, 0xc013020b80}, {{0xb, 0x0}, {0xc036e9a760, 0xa}, 0x2364c,
  {0x22e03622, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.6/baseapp/msg_service_router.go:117
  +0x350\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x26d7a70,
  0xc000130020}, {0x26e4c80, 0xc013020b80}, {{0xb, 0x0}, {0xc036e9a760, 0xa}, 0x2364c,
  ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.6/baseapp/baseapp.go:736
  +0x5c5\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000d751e0, 0x3,
  {0xc00dcb0000, 0x100, 0x100})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.6/baseapp/baseapp.go:693
  +0xd2c\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).DeliverTx(0xc000d751e0,
  {{0xc00dcb0000?, 0xc008e379e0?, 0x20?}})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.6/baseapp/abci.go:276
  +0x193\ngithub.com/ingenuity-build/quicksilver/app.(*Quicksilver).DeliverTx(0xc008e378e0?,
  {{0xc00dcb0000?, 0x20?, 0xc008e37900?}})\n\tgithub.com/ingenuity-build/quicksilver/app/app.go:783
  +0xd2\ngithub.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc000fab7a0,
  {{0xc00dcb0000?, 0x0?, 0xc000fab7a0?}})\n\tgithub.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:93
  +0x105\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc0144d9940?,
  {{0xc00dcb0000?, 0x20?, 0xb?}})\n\tgithub.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:85
  +0x26\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x26d8838?, 0xc0057c93e0},
  {0x26ddbf8, 0xc000db9180}, 0xc00212e5a0, {0x26e3f88, 0xc000dd1470}, 0x2364b?)\n\tgithub.com/tendermint/tendermint@v0.34.19/state/execution.go:320
  +0x822\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb,
  0x0}, {0xc002501a90, 0x8}}, {0xc002501aa0, 0xa}, 0x1, 0x2364b, {{0xc0302fba60, ...},
  ...}, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.34.19/state/execution.go:140
  +0x171\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000f4fc00,
  0x2364c)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1655 +0x9fd\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000f4fc00,
  0x2364c)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1564 +0x305\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1499
  +0x87\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc000f4fc00,
  0x2364c, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1537
  +0xbea\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc000f4fc00,
  0xc01c8b5a40, {0xc011971560, 0x28})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:2151
  +0xb7c\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000f4fc00,
  0xc01c8b5a40, {0xc011971560?, 0xc0124fdf00?})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:1949
  +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000f4fc00,
  {{0x26bd660?, 0xc017f04430?}, {0xc011971560?, 0x0?}})\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:856
  +0x44b\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000f4fc00,
  0x0)\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:763 +0x419\ncreated
  by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.19/consensus/state.go:379
  +0x12d\n: panic"
```

**Comment by joe-bowman** [comment]
resolved in #225
